
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html


plugin: amazon.aws.aws_ec2
regions:
  - eu-west-3
# filters:
#   # All instances with their `Environment` tag set to `dev`
#   tag:Environment: dev
#   # All dev and QA hosts
#   tag:Environment:
#     - dev
#     - qa
#   instance.group-id: sg-xxxxxxxx

filters:
  tag:filter: vm00

hostnames:
  - tag:Name
keyed_groups:
  - key: tags
  # - key: tags['Role']
  #   parent_group: "project"

compose:
  ansible_host: private_ip_address

# groups:
#   front: "'front' in tags.Role"
#   api: "'api' in tags.Role"
#   db: "'db' in tags.Role"
